### ISSUE TITLE
Additional hooks to customise table

### ISSUE THREAD

**Issue by colin-lamed** [andrewthad/yesod-table#6]
It would be nice to be able to influence the table rendering if desired.

In my case, I have applied the API to a table which uses bootstrap-sortable for column sorting, and also allows the user to click on a row.

I wrote an alternative to the `buildBootstrap` which allowed me to customise the table style, and control the tr rendering:

``` haskell
renderTable :: T.Table App a
            -> [a]
            -> Text                    -- the table class, applied as: table b  = asWidgetIO [whamlet| <table .#{tClass}>^{b} |]
            -> (a -> Widget -> Widget) -- an alternative tr function, which takes the "a" row data
            -> Widget
```

Then I can call this like:

``` haskell
let tClass = "table table-bordered table-striped table-hover sortable"
    tr v b = [whamlet|
               <tr onclick=window.location.href='@{NextR v}'>^{b}
             |]
...
^{renderTable table verbs tClass tr}
```

However I would also like to provide some attributes to the `th`. But this looks like it would require modifications to the Column type, to associate the extra information with the column.

one possible approach would be to provide a header render function, in addition to the cell render function. e.g.:

``` haskell
myTable = mempty
  <> T.widget "Col1" renderCellForCol1 (\b -> [whamlet| <th data-defaultsort="asc">^{b} |])
  <> T.widget "Col2" renderCellForCol2 (\b -> [whamlet| <th data-defaultsort="disabled">^{b} |])
```

**Comment by andrewthad** [comment]
That's a cool use of yesod-table, and thanks for bringing up this issue. I like what you're doing with the custom `tr` in your rendering function. I think I have a simpler fix for getting the custom `th`s to be the way you need them.

So, right now `Column` is defined as:

```
data Column site a = Column
  { header :: !(WidgetT site IO ())
  , cell :: !(a -> WidgetT site IO ()) 
  }
```

My thought is that, instead of changing this data type at all, I change the meaning of the `header` field. Right now, `header` represents a `WidgetT site IO ()` that will be wrapped inside of a `th`. Instead, it could mean a `WidgetT site IO ()` that includes its own `th`. All of the convenience functions in yesod-table would by default add the `th` around your text, and `T.singleton` alone would give you the power that you're looking for. Of course, a similar argument could be made to change the meaning of `cell` in a similar way to allow flexibility with the `td`s, but I'd probably hold off on this until a use case came up.

With my proposed changes, your final example would instead look like this:

```
myTable = mempty
  <> T.singleton [whamlet|<th data-defaultsort="asc">Col1|] renderCellForCol1
  <> T.singleton [whamlet|<th data-defaultsort="disabled">Col2|] renderCellForCol2
```

Let me know if this will satisfy your use case, and I can implement the changes.

For posterity (since I was previously unfamiliar with bootstrap-sortable), the bootstrap-sortable project is [here](https://github.com/drvic10k/bootstrap-sortable) and an example of it is [here](http://drvic10k.github.io/bootstrap-sortable/).

**Comment by colin-lamed** [comment]
Yes, I think that will work nicely! Thanks for the response!

**Comment by andrewthad** [comment]
There is now a release with these changes: https://github.com/andrewthad/yesod-table/releases/tag/2.0.0
It is on hackage as well.

I went ahead and pushed the requirement to wrap cells with `td` into `Column` as well. Consequently, the solution to the example should actually look like this:

```
myTable = mempty
  <> T.singleton [whamlet|<th data-defaultsort="asc">Col1|] (td . renderCellForCol1)
  <> T.singleton [whamlet|<th data-defaultsort="disabled">Col2|] (td . renderCellForCol2)
  where td a = [whamlet|<td>^{a}|]
```

You'll also have to modify your `renderTable` function to not add `th` and `td` around headers and cells, respectively.

After trying this out, please confirm that it works because I haven't actually tested this new code yet.

**Comment by colin-lamed** [comment]
I've tried it and it works great. Thanks a lot!
